language: java
jdk:
  - oraclejdk12
  
dist: trusty

addons:
  sonarcloud:
    organization: "hazielgr"
    token:
      secure: "fc6439f89c4c7c7f54e9be6c3133d2bab022f599"

script:
  - ant build
  - sonar-scanner