language: java
jdk:
  - oraclejdk12
 
dist: trusty

addons:
  sonarcloud:
    organization: "hazielgr"
    token:
      secure: "07f80f50bf33a6dbda8f98754c9ff7a5e50f53f0"
      
script:
  - ant build
  - sonar-scanner