language: java
jdk:
  - oraclejdk12
  
dist: trusty

addons:
  sonarcloud:
    organization: "hazielgr"
    token:
      secure: "b81b8574a4c6bff45139a1602730d5c09eab0887"

script:
  - ant build
  - sonar-scanner