language: java
jdk:
  - oraclejdk12
 
dist: trusty

addons:
  sonarcloud:
    organization: "hazielgr"
    token:
      secure: "c86146e11a3e258576e08b6f4f18346d05c42a94"
      
script:
  - ant build
  - sonar-scanner