language: java
jdk:
  - oraclejdk12
 
dist: trusty

addons:
  sonarcloud:
    organization: "hazielgr"
    token:
      secure: "a1fa8c1e856686bf9dc6d502a5e3e6b061da184b"
      
script:
  - ant build
  - sonar-scanner